"""clerk auth: reemplaza password por clerk_user_id

Revision ID: 4459ee7b06ea
Revises: 992e73149e10
Create Date: 2026-09-07 11:22:09.695920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4459ee7b06ea'
down_revision: Union[str, Sequence[str], None] = '992e73149e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Los usuarios existentes (creados con el login propio, pre-Clerk) no
    # tienen clerk_user_id y no pueden migrarse: se recrean solos la
    # primera vez que cada quien inicia sesion con Clerk.
    op.execute("DELETE FROM usuarios")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('clerk_user_id', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_usuarios_clerk_user_id'), 'usuarios', ['clerk_user_id'], unique=True)
    op.drop_column('usuarios', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_usuarios_clerk_user_id'), table_name='usuarios')
    op.drop_column('usuarios', 'clerk_user_id')
    # ### end Alembic commands ###
