"""acceso: modo solo lectura y username

Revision ID: 4542c3a02a78
Revises: d2fc57519205
Create Date: 2026-09-25 09:39:55.242351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4542c3a02a78'
down_revision: Union[str, Sequence[str], None] = 'd2fc57519205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('permite_acciones', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('usuarios', sa.Column('username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'username')
    op.drop_column('clientes', 'permite_acciones')
    # ### end Alembic commands ###
