"""modelo inicial: empresas, usuarios, periodos, saldos, indicadores

Revision ID: 992e73149e10
Revises: 
Create Date: 2026-09-07 00:04:01.534462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992e73149e10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('regimen', sa.String(length=100), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('meses_colchon_caja', sa.Float(), nullable=False),
    sa.Column('wacc_tasa_libre_riesgo', sa.Float(), nullable=False),
    sa.Column('wacc_prima_mercado', sa.Float(), nullable=False),
    sa.Column('wacc_beta', sa.Float(), nullable=False),
    sa.Column('wacc_riesgo_pais', sa.Float(), nullable=False),
    sa.Column('wacc_prima_tamano', sa.Float(), nullable=False),
    sa.Column('wacc_costo_deuda_tea', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_ruc'), 'empresas', ['ruc'], unique=True)
    op.create_table('periodos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('mensual', 'trimestral', 'anual', name='periodotipo'), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'tipo', 'anio', 'mes', name='uq_periodo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'cliente', name='rol'), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('indicadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('calculado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo_id', 'nombre', name='uq_indicador_periodo')
    )
    op.create_index(op.f('ix_indicadores_nombre'), 'indicadores', ['nombre'], unique=False)
    op.create_table('saldos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('fuente', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saldos_clave'), 'saldos', ['clave'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saldos_clave'), table_name='saldos')
    op.drop_table('saldos')
    op.drop_index(op.f('ix_indicadores_nombre'), table_name='indicadores')
    op.drop_table('indicadores')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('periodos')
    op.drop_index(op.f('ix_empresas_ruc'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
