"""portal cliente: reemplaza el modelo financiero

Revision ID: d2fc57519205
Revises: 4459ee7b06ea
Create Date: 2026-09-25 09:04:53.676500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fc57519205'
down_revision: Union[str, Sequence[str], None] = '4459ee7b06ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # El prototipo financiero (empresas/periodos/saldos/indicadores) se
    # reemplaza por el modelo del portal. Solo habia datos de prueba.
    bind = op.get_bind()
    insp = sa.inspect(bind)
    for tabla in ("indicadores", "saldos", "periodos", "usuarios", "empresas"):
        if insp.has_table(tabla):
            op.drop_table(tabla)
    if bind.dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS rol")
        op.execute("DROP TYPE IF EXISTS periodotipo")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=40), nullable=False),
    sa.Column('t', sa.String(length=300), nullable=False),
    sa.Column('d', sa.Text(), nullable=False),
    sa.Column('modo', sa.String(length=60), nullable=False),
    sa.Column('dur', sa.String(length=40), nullable=False),
    sa.Column('prof', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('grupo', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=300), nullable=False),
    sa.Column('lider', sa.String(length=200), nullable=False),
    sa.Column('areas', sa.JSON(), nullable=False),
    sa.Column('fuente_datos', sa.Text(), nullable=False),
    sa.Column('analytics_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('decisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.String(length=10), nullable=False),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('por', sa.String(length=200), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'clave')
    )
    op.create_index(op.f('ix_decisiones_cliente_id'), 'decisiones', ['cliente_id'], unique=False)
    op.create_table('diagnosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.String(length=10), nullable=False),
    sa.Column('empresa_codigo', sa.String(length=20), nullable=True),
    sa.Column('area', sa.String(length=40), nullable=False),
    sa.Column('est', sa.String(length=40), nullable=False),
    sa.Column('av', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'empresa_codigo', 'area')
    )
    op.create_index(op.f('ix_diagnosticos_cliente_id'), 'diagnosticos', ['cliente_id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.String(length=10), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ruc_num', sa.String(length=60), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('analytics', sa.JSON(), nullable=True),
    sa.Column('servicios', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cliente_id'), 'empresas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_empresas_codigo'), 'empresas', ['codigo'], unique=True)
    op.create_table('intereses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.String(length=10), nullable=False),
    sa.Column('clave', sa.String(length=300), nullable=False),
    sa.Column('por', sa.String(length=200), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'clave')
    )
    op.create_index(op.f('ix_intereses_cliente_id'), 'intereses', ['cliente_id'], unique=False)
    op.create_table('kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.String(length=10), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=40), nullable=False),
    sa.Column('sub', sa.String(length=120), nullable=False),
    sa.Column('n', sa.String(length=200), nullable=False),
    sa.Column('est', sa.String(length=20), nullable=False),
    sa.Column('fuente', sa.String(length=300), nullable=False),
    sa.Column('base', sa.String(length=200), nullable=False),
    sa.Column('meta', sa.String(length=200), nullable=False),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('viz', sa.String(length=20), nullable=True),
    sa.Column('sub2', sa.String(length=300), nullable=False),
    sa.Column('home', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('ref', sa.Float(), nullable=True),
    sa.Column('refl', sa.String(length=200), nullable=True),
    sa.Column('parts', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpis_cliente_id'), 'kpis', ['cliente_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'cliente', name='rol'), nullable=False),
    sa.Column('cliente_id', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_clerk_user_id'), 'usuarios', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=20), nullable=False),
    sa.Column('empresa_codigo', sa.String(length=20), nullable=False),
    sa.Column('area', sa.String(length=40), nullable=False),
    sa.Column('fase', sa.String(length=10), nullable=False),
    sa.Column('num', sa.String(length=20), nullable=False),
    sa.Column('act', sa.Text(), nullable=False),
    sa.Column('ent', sa.Text(), nullable=False),
    sa.Column('est', sa.String(length=40), nullable=False),
    sa.Column('av', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_codigo'], ['empresas.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actividades_empresa_codigo'), 'actividades', ['empresa_codigo'], unique=False)
    op.create_index(op.f('ix_actividades_uid'), 'actividades', ['uid'], unique=False)
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_codigo', sa.String(length=20), nullable=False),
    sa.Column('cod', sa.String(length=40), nullable=False),
    sa.Column('doc', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('area', sa.String(length=40), nullable=False),
    sa.Column('sub', sa.String(length=200), nullable=False),
    sa.Column('resp', sa.String(length=200), nullable=False),
    sa.Column('est', sa.String(length=40), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('enviado_nombre', sa.String(length=300), nullable=True),
    sa.Column('enviado_url', sa.String(length=600), nullable=True),
    sa.Column('enviado_fecha', sa.Date(), nullable=True),
    sa.Column('enviado_por', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['empresa_codigo'], ['empresas.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_codigo', 'cod')
    )
    op.create_index(op.f('ix_checklist_empresa_codigo'), 'checklist', ['empresa_codigo'], unique=False)
    op.create_table('fases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_codigo', sa.String(length=20), nullable=False),
    sa.Column('area', sa.String(length=40), nullable=False),
    sa.Column('fase', sa.String(length=10), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('paso', sa.Integer(), nullable=False),
    sa.Column('contratada', sa.Boolean(), nullable=False),
    sa.Column('alc', sa.String(length=60), nullable=False),
    sa.Column('av', sa.Integer(), nullable=False),
    sa.Column('gate', sa.String(length=60), nullable=False),
    sa.Column('crit', sa.Text(), nullable=False),
    sa.Column('ini', sa.Date(), nullable=True),
    sa.Column('fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_codigo'], ['empresas.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fases_empresa_codigo'), 'fases', ['empresa_codigo'], unique=False)
    op.create_table('fugas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_codigo', sa.String(length=20), nullable=False),
    sa.Column('fuga', sa.Text(), nullable=False),
    sa.Column('area', sa.String(length=40), nullable=False),
    sa.Column('prob', sa.String(length=20), nullable=False),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('trat', sa.Text(), nullable=False),
    sa.Column('est', sa.String(length=20), nullable=False),
    sa.Column('fuente', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['empresa_codigo'], ['empresas.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fugas_empresa_codigo'), 'fugas', ['empresa_codigo'], unique=False)
    op.create_table('kpi_valores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('empresa_codigo', sa.String(length=20), nullable=False),
    sa.Column('val', sa.String(length=200), nullable=False),
    sa.Column('num', sa.Float(), nullable=True),
    sa.Column('sub2x', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kpi_id', 'empresa_codigo')
    )
    op.create_index(op.f('ix_kpi_valores_kpi_id'), 'kpi_valores', ['kpi_id'], unique=False)
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_codigo', sa.String(length=20), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('sol', sa.Text(), nullable=False),
    sa.Column('area', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('plazo', sa.Integer(), nullable=False),
    sa.Column('est', sa.String(length=40), nullable=False),
    sa.Column('atendida', sa.Date(), nullable=True),
    sa.Column('creada_por', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['empresa_codigo'], ['empresas.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_codigo', 'n')
    )
    op.create_index(op.f('ix_solicitudes_empresa_codigo'), 'solicitudes', ['empresa_codigo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitudes_empresa_codigo'), table_name='solicitudes')
    op.drop_table('solicitudes')
    op.drop_index(op.f('ix_kpi_valores_kpi_id'), table_name='kpi_valores')
    op.drop_table('kpi_valores')
    op.drop_index(op.f('ix_fugas_empresa_codigo'), table_name='fugas')
    op.drop_table('fugas')
    op.drop_index(op.f('ix_fases_empresa_codigo'), table_name='fases')
    op.drop_table('fases')
    op.drop_index(op.f('ix_checklist_empresa_codigo'), table_name='checklist')
    op.drop_table('checklist')
    op.drop_index(op.f('ix_actividades_uid'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_empresa_codigo'), table_name='actividades')
    op.drop_table('actividades')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_clerk_user_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_kpis_cliente_id'), table_name='kpis')
    op.drop_table('kpis')
    op.drop_index(op.f('ix_intereses_cliente_id'), table_name='intereses')
    op.drop_table('intereses')
    op.drop_index(op.f('ix_empresas_codigo'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_cliente_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_diagnosticos_cliente_id'), table_name='diagnosticos')
    op.drop_table('diagnosticos')
    op.drop_index(op.f('ix_decisiones_cliente_id'), table_name='decisiones')
    op.drop_table('decisiones')
    op.drop_table('config')
    op.drop_table('clientes')
    op.drop_table('academia')
    # ### end Alembic commands ###
